@hostname = localhost
@port = 7265

GET https://{{hostname}}:{{port}}/api/tickets
Accept: application/json

### Test 1: Dodawanie nowego zg³oszenia (POST)
POST https://localhost:{{port}}/api/tickets
Content-Type: application/json

{
  "title": "B³¹d drukarki",
  "description": "Zaciêcie papieru w pokoju 205"
}

### Test 2: Pobieranie po ID (Zmieñ '1' na ID które dosta³aœ powy¿ej)
GET https://localhost:{{port}}/api/tickets/1
Accept: application/json

### Test 3: Próba pobrania nieistniej¹cego ID (Status 404)
GET https://localhost:{{port}}/api/tickets/999
Accept: application/json

### Test 4: Walidacja (Wyœlij za krótki tytu³ - Status 400)
POST https://localhost:{{port}}/api/tickets
Content-Type: application/json

{
  "title": "A",
  "description": "Test walidacji"
}